routes/web.php
        Route::get('/settings', 'ClassroomUserController@getSettingsView')->name('.settings');
        Route::get('/settings/t/invoice', 'ClassroomInvoiceSettingController@show')->name('.settings.teacher.invoice');
        Route::patch('/settings/t/invoice', 'ClassroomInvoiceSettingController@update')->name('.settings.teacher.invoice.update');

        Route::get('/settings/s/parent', 'ClassroomStudentController@editParentSettings')->name('.settings.student.parent');
        Route::patch('/settings/s/parent', 'ClassroomStudentController@updateParentSettings')->name('.settings.student.parent.update');

        // Billing
        Route::get('billing_history', 'ClassroomBillingController@history')->name('.billing_history');
        Route::get('download_invoice/{invoice_id}', function($invoice_id){
            return request()->user()->downloadInvoice($invoice_id, [
                'vendor' => config('app.name'),
                'product' => 'Classroom',
            ], 'board_invoice');
        })->name('.download_invoice');
    });
});

// Teacher Routes
Route::middleware('teacher_auth')->prefix('t')->name('teacher')->group(function(){
    // Getting started
    Route::get('getting-started', 'TeacherController@getGettingStartedView');
    Route::patch('/update', 'TeacherController@update')->name('.update');
});

// Parents routes
Route::prefix('p')->name('parent')->middleware('parent_auth')->group(function(){
    // Getting started
    Route::get('getting-started', 'StudentParentController@get_getting_started_view');
    Route::patch('/update', 'StudentParentController@update')->name('.update');
});

Route::view('/r/spm-state-papers', 'board_resources.spm_state_papers');

//Post and delete answers
Route::middleware('optimizeImages')->group(function () {
    Route::post('/questions/{question}/answers', 'AnswerController@store')->name('answers.store');
});

// Answers
Route::prefix('/answers')->name('answers')->group(function(){
    Route::get('/{answer}/edit', 'AnswerController@edit')->name('.edit');
    Route::patch('/{answer}/update', 'AnswerController@update')->name('.update');
    Route::delete('/{answer}', 'AnswerController@destroy')->name('.delete');

    Route::post('/{answer}/upvotes', 'AnswerUpvoteController@toggleUpvote')->name('.upvote');
    Route::post('/{answer}/check', 'AnswerCheckController@update')->name('.check');
});

// Question comments
Route::name('question_comments')->group(function(){
    Route::post('/questions/{question}/comments', 'QuestionCommentController@store')->name('.store');
    Route::delete('/questions/comments/{id}', 'QuestionCommentController@destroy')->name('.delete');
});

// Answer comments
Route::name('answer_comments')->group(function(){
    Route::post('/answers/{answer}/comments', 'AnswerCommentController@store')->name('.store');
    Route::delete('/answers/comments/{id}', 'AnswerCommentController@destroy')->name('.delete');
});

//Upvote/check for questions and answers
Route::post('/questions/{question}/upvotes', 'QuestionUpvoteController@toggleUpvote')->name('questions.upvote');

// Users
Route::prefix('/users')->name('users')->group(function(){
    // Questions/Answers
    Route::get('/{user}', 'UserController@show')->name('.show');
    Route::get('/{user}/questions', 'UserController@questions')->name('.questions');

    // Notes
    Route::get('/{user}/notes', 'UserController@notes')->name('.notes');

    // Articles
    Route::prefix('/{user}/articles')->name('.articles')->group(function(){
        Route::get('/', 'ArticleController@index');
    });

    Route::prefix('/articles')->name('.articles')->group(function(){
        Route::get('/create', 'ArticleController@create')->name('.create');
        Route::post('/store', 'ArticleController@store')->name('.store');

        Route::prefix('/{article}')->group(function(){
            Route::get('/show', 'ArticleController@show')->name('.show');
            Route::get('/edit', 'ArticleController@edit')->name('.edit');
            Route::patch('/update', 'ArticleController@update')->name('.update');
            Route::delete('/delete', 'ArticleController@delete')->name('.delete');
        });
    });

    // Account
    Route::patch('/{user}/account', 'UserController@accountSettings')->name('.account.settings');
    // Password
    Route::post('/{user}/password', 'Auth\ChangePasswordController@change')->name('.changePassword');
    // Switch Account Type
    Route::post('/{user}/account/switch-type', 'UserController@switchAccountType')->name('.account.switch_account_type');
});

// Settings
Route::prefix('/settings')->name('settings')->group(function(){
    // Profile
    Route::get('/', 'SettingsController@profile')->name('');
    // Password
    Route::get('/password', 'SettingsController@password')->name('.password');
    // Account
    Route::get('/account', 'SettingsController@account')->name('.account');
});

// Mark as Read
Route::middleware('auth')->get('/markAsRead', function(){
    $user = auth()->user();
    $user->unreadNotifications->markAsRead();
})->name('markAsRead');

// Board Pass
Route::get('/board-pass', 'BoardPassController@getBoardPassView')->name('board_pass');

Route::get('/coins', 'ProductController@index')->name('products.coins');

// Board Pass AJAX routes
Route::post('/board-pass/end-at', 'BoardPassController@getEndAtDate');
Route::post('/board-pass/no-of-additional-subscription-months', 'BoardPassController@getNoOfAdditionalSubscriptionMonths');
Route::post('/board-pass/amount-of-coins', 'BoardPassController@getAmountOfCoins');
Route::post('/board-pass/discount', 'BoardPassController@getDiscount');

Route::middleware('auth')->group(function(){
    Route::post('/products/{product}/purchase', 'ProductController@purchase')->name('products.purchase');
    Route::post('/board-pass/purchase', 'BoardPassController@purchase')->name('board_pass.purchase');

    Route::get('/payment', 'PaymentController@getUpdateView')->name('payment');
    Route::post('/payment/default/update', 'PaymentController@updateDefaultPaymentMethod')->name('payment.update_default_payment_method');
    Route::post('/payment/add', 'PaymentController@addPaymentMethod')->name('payment.add_payment_method');
    Route::post('/payment/invoice/{invoice}/download', 'PaymentController@downloadInvoice')->name('payment.download_invoice');

    Route::post('/topical-past-papers/claim/{past_paper}', 'TopicalPastPaperController@claim')->name('topical_past_papers.claim');

    Route::get('/my-coins', 'CoinController@show')->name('coins.show');
    // Route::get('/my-resources', 'ResourceController@show')->name('resources.show');

    // Recommend questions/answers routes
    Route::post('/questions/{question}/recommend', 'QuestionController@recommend')->name('questions.recommend');
    Route::post('/answers/{answer}/recommend', 'AnswerController@recommend')->name('answers.recommend');
});

Route::post('error/feedback', function(){
    // Data for email
    $email = request()->email ?? null;
    $feedback = request()->feedback;
    // To redirect users after submitting form
    $exam_board = request()->exam_board ?? null;

    // Send error feedback form via email
    Mail::to( config('mail.report_to.address') )->send(new ErrorFeedback($email, $feedback));

    if( !is_null($exam_board) ) {
        return redirect()->route('questions.index', $exam_board)->withSuccess('Thank you for your feedback!');
    }
    return redirect()->route('/')->withSuccess('Thank you for your feedback!');

})->name('errorFeedback');

// Events
Route::prefix('events')->name('events')->group(function(){
    Route::prefix('/2020')->name('.2020')->group(function(){
        Route::get('/math-board-quiz', 'EventController@getMathQuiz2020View')->name('.get_math_board_quiz_view');
        Route::post('/math-board-quiz', 'EventController@mathQuiz2020')->name('.math_board_quiz.quiz');
        Route::get('/math-board-quiz/thank-you/{is_existing_user}', 'EventController@getMathQuiz2020ThankYouView')->name('.math_board_quiz.thank_you');

        Route::middleware('auth')->group(function(){
            Route::get('/stoichiometry-mania/register', 'EventController@getStoichiometryMania2020RegisterView')->name('.get_stoichiometry_mania_register_view');
            Route::post('/stoichiometry-mania', 'EventController@stoichiometryMania2020Register')->name('.stoichiometry_mania_register');
        });
    });
});

// Route::view('/physical-resources', 'physical_resources')->name('physical_resources');
Route::view('/subject-chapter-id-reference', 'subject_chapter_id_reference')->name('subject_chapter_id_reference');

// Bug Report
Route::post('/bug_report', 'BugReportController@store')->name('bug_reports.store');

// Exam Board specific routes
Route::prefix('/{exam_board}')->group(function(){
    //Subjects and chapters
    Route::get('/subjects/{subject}', 'SubjectController@show')->name('subject');
    Route::get('/chapters/{chapter}', 'ChapterController@show')->name('chapter');

    Route::get('/questions/create', 'QuestionController@create')->name('questions.create');

    // Resource route for questions
    Route::resource('/questions', 'QuestionController');
    // Overriding resource routes
    Route::get('/', 'QuestionController@index')->name('questions.index');
    Route::get('/questions/{id}/{slug?}', 'QuestionController@show')->name('questions.show');
    Route::middleware('optimizeImages')->group(function () {
        Route::post('/questions', 'QuestionController@store')->name('questions.store');
    });

    Route::get('/search', 'SearchController@index')->name('search.index');

    // Resources
    Route::middleware('resource')->group(function(){
        // Past Papers
        Route::prefix('/past-papers')->name('past_papers')->group(function(){
            Route::get('/', 'PastPaperController@getHomeView')->name('.home');
            Route::get('/subjects/{subject?}', 'PastPaperController@subjectShow')->name('.subject_show');

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use CyrildeWit\EloquentViewable\Viewable;
use CyrildeWit\EloquentViewable\Contracts\Viewable as ViewableContract;

class Article extends Model implements ViewableContract
{
    use Viewable;

    //Allow mass assignment to all variables in the model
    protected $guarded = [];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * -----------------
     * ACCESSORS
     * -----------------
     */
    /**
     * Returns relative path of cover image
     * @return string
     */
    public function getCoverImgRelativeUrlAttribute()
    {
        return $this->getOriginal('cover_img');
    }

    /**
     * Returns comma-delimited string tags
     * @return string
     */
    public function getTagsCommaDelimitedStrAttribute()
    {
        return $this->getOriginal('tags');
    }

    /**
     * Returns tags in array
     * @return array
     */
    public function getTagsAttribute($value)
    {
        return array_filter(explode(',', $value));
    }

    /**
     * Get full cover image URL path
     * @return string
     */
    public function getCoverImgAttribute($value)
    {
        return !is_null($value) ? Storage::cloud()->url($value)
                                : asset('img/essential/article_default_cover_img.png');
    }

    /**
     * Returns show URL
     * @return string
     */
    public function getShowUrlAttribute()
    {
        return route('users.articles.show', $this->id);
    }

    /**
     * --------------------
     * HELPERS
     * --------------------
     */
    /**
     * Updates article cover image
     * @param $img
     */
    public function updateCoverImage($img)
    {
        if( is_null($img) ) {
            throw new \Exception("Cover image cannot be empty");
        }

        //Delete existing user profile image if any
        if( !is_null($this->cover_img_relative_url) ){
            Storage::cloud()->delete( $this->cover_img_relative_url );
        }

        $img->store('articles/', 's3');
        $filename = $img->hashName();
        $url = "articles/{$filename}";

        $this->update(['cover_img' => $url]);
    }

    /**
     * Returns Collection of Articles by user
     * @param int $take
     * @return Collection
     */
    public function getMoreArticlesByUsers($take = 3)
    {
        return self::where('id', '!=', $this->id)->where('user_id', $this->user_id)->orderByDesc('created_at')->take($take)->get();
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use App\User;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    /**
     * Index article
     */
    public function index(User $user)
    {
        if(!$user->is_teacher()) {
            return redirect()->back()->withError('User\'s account type cannot post articles!');
        }
        $articles = $user->articles()->latest()->paginate(10);
        return view('forum.users.profile.articles', compact('user', 'articles'));
    }

    /**
     * Show article
     */
    public function create(User $user, Article $article)
    {
        $this->authorize('create_store', Article::class);
        $is_edit = false;
        $article = null;
        return view('forum.users.profile.articles.create_edit', compact('user', 'is_edit', 'article'));
    }

    /**
     * Store article
     */
    public function store(User $user, Article $article)
    {
        $this->authorize('create_store', Article::class);
        // Validation
        request()->validate([
            'title' => 'required|string|max:100',
            'description' => 'required|string',
            'body' => 'required|string',
            'tags' => 'nullable',
            'cover_img' => 'nullable|mimes:jpeg,png,jpg,gif,svg',
        ]);

        $user = auth()->user();
        // Create Article
        $article = $user->articles()->create([
                        'title' => request('title'),
                        'description' => request('description'),
                        'body' => request('body'),
                        'tags' => request('tags'),
                    ]);
        return redirect()->route('users.articles.show', $article->id)->with('success', 'Article posted successfully!');
    }

    /**
     * Edit article
     */
    public function edit(User $user, Article $article)
    {
        $this->authorize('edit_update', $article);
        $is_edit = true;
        return view('forum.users.profile.articles.create_edit', compact('user', 'is_edit', 'article'));
    }

    public function update(Article $article)
    {
        $this->authorize('edit_update', $article);
        // Validation
        request()->validate([
            'title' => 'required|string|max:100',
            'description' => 'required|string',
            'body' => 'required|string',
            'tags' => 'nullable',
            'cover_img' => 'nullable|mimes:jpeg,png,jpg,gif,svg',
        ]);

        // Update article
        $article->update([
            'title' => request('title'),
            'description' => request('description'),
            'body' => request('body'),
            'tags' => request('tags'),
        ]);

        // Save cover image
        if(request()->has('cover_img') && !is_null(request()->file('cover_img'))) {
            $article->updateCoverImage( request()->file('cover_img') );
        }

        return redirect()->route('users.articles.show', $article->id)->withSuccess('Article updated successfully!');
    }

    /**
     * Show article
     */
    public function show(User $user, Article $article)
    {
        views($article)->record();
        return view('forum.users.profile.articles.show', compact('user', 'article'));
    }

    /**
     * Delete Article
     */
    public function delete(Article $article)
    {
        $this->authorize('delete', $article);
        // Delete article
        $article->delete();
        return redirect()->route('users.articles', $article->user->username)->with('error', 'Article deleted successfully!');
    }
}

resources/views/forum/users/profile/articles/create_edit.blade.php
@extends('forum.layouts.app')

@section('meta')
<title>Write Article | {{ config('app.name') }}</title>
@endsection

@section('styles')
{{-- Selectize --}}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/css/selectize.min.css" integrity="sha512-87wkTHUArAnTBwQ5XL6+G68i54R3TXYDZoXewRsdhIv/ztcEr2Z1Mrk+aXBCKOZUtih0XWiBhXv3/bWjHTL2Bw==" crossorigin="anonymous" />
@endsection

@section('content')
@include('main.navs.header')

<div class="py-3"></div>

<div class="container">
    <div class="row">
        <div class="col-12 col-lg-9 mb-2">
            <div class="maxw-740px mx-auto">
                <a class="d-block mb-2 inactive font-size2 gray2" href="{{ route('/') }}">< Back to Home</a>

                <h1 class="font-size7">{{ $is_edit ? 'Edit Article' : 'Write Article' }}</h1>

                <div class="panel">
                    @component('forum.users.profile.articles.common.form', ['is_edit' => $is_edit, 'article' => $article])
                    @endcomponent
                </div>
            </div>
        </div>
        <div class="col-12 col-lg-3 mb-2">
        </div>
    </div>
</div>

<div class="py-3"></div>
@endsection

@section('js_dependencies')
{{-- TinyMCE --}}
<script src="https://cdn.tiny.cloud/1/si4jvonmpvtlfypotvf9zu2vci2zsjavfd4v1oyvnzncszag/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>    {{-- KaTeX --}}
<script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-alpha1/katex.min.js" integrity="sha384-GR8SEkOO1rBN/jnOcQDFcFmwXAevSLx7/Io9Ps1rkxWp983ZIuUGfxivlF/5f5eJ" crossorigin="anonymous"></script>
@endsection

@section('scripts')
{{-- Sweet Alert 2 --}}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
{{-- Selectize.js --}}
<script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/standalone/selectize.min.js" integrity="sha512-hgoywpb1bcTi1B5kKwogCTG4cvTzDmFCJZWjit4ZimDIgXu7Dwsreq8GOQjKVUxFwxCWkLcJN5EN0W0aOngs4g==" crossorigin="anonymous"></script>
<script>
$(function(){
    // Tags Input
    var options = [
        {value: 'Opinion'},
        {value: 'Teaching Techniques'},
        {value: 'Exam Tips'},
    ];

    var items = options.map(x => x.name);
    $('.articleTagsInput').selectize({
        plugins: ['remove_button'],
        delimiter: ',',
        persist: false,
        maxItems: 3,
        options: options,
        items: items,
        labelField: 'value',
        valueField: 'value',
        create: function(input) {
            return {
                value: input,
                text: input
            }
        }
    });
});
</script>
@endsection

resources/views/forum/users/profile/articles/show.blade.php
@extends('main.layouts.app')

@section('meta')
<title>{{ $article->title }} | {{ config('app.name') }}</title>
<meta name="description" content="{{ $article->description }}">

<meta property="og:image" content="{{ $article->cover_img }}" />
<meta property="og:type" content="article" />
@endsection

@section('content')
<div class="container">
    <div class="maxw-740px mx-auto">

        <div class="py-1"></div>
        {{-- Back Button --}}
        <a href="{{ route('users.articles', $article->user->username) }}" class="d-inline-block gray2 underline-on-hover mb-2">< Back to {{ $article->user->username }} Articles</a>

        <div class="panel">
            <img class="blog__cover-img" src="{{ $article->cover_img }}" alt="" class="cover-img mb-2">

            <div class="blog-content">
                <div class="mb-3">
                    <div class="mt-2">
                        @foreach($article->tags as $tag)
                            <a href="javascript:void" class="blog-tag mb-1">{{ $tag }}</a>
                        @endforeach
                    </div>
                    <h1 class="font-size11"><b>{{ $article->title }}</b></h1>

                    <div class="py-1"></div>

                    {{-- Share Buttons --}}
                    <div class="shareIcons"></div>

                    <div class="py-1"></div>

                    {{-- Edit/Delete Buttons --}}
                    @can('edit_update', $article)
                        <div>
                            <a href="{{ route('users.articles.edit', $article->id) }}" class="d-inline-block underline-on-hover mr-1 mb-2"><span class="iconify" data-icon="bx:bx-edit" data-inline="false"></span> Edit</a>
                            @can('delete', $article)
                                <form action="{{ route('users.articles.delete', $article->id) }}" class="d-inline-block mb-2" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="red deleteButton p-0 underline-on-hover">
                                        <span class="iconify" data-icon="carbon:trash-can" data-inline="false"></span>
                                        Delete
                                    </button>
                                </form>
                            @endcan
                        </div>
                    @endcan
                </div>

                <p><b>{{ views($article)->count() }} views</b></p>

                {{-- Author --}}
                <div class="d-flex justify-content-start align-items-start border-top border-bottom py-3">
                    <a href="{{ $article->user->show_url }}">
                        <img src="{{ $article->user->avatar }}" class="avatar mr-2" alt="Author Avatar">
                    </a>
                    <div>
                        <h4 class="font-size3 font-weight500 mb-1">
                            <a href="{{ $article->user->show_url }}" class="font-size-inherit color-inherit">
                                {{ $article->user->name }}
                            </a>
                        </h4>
                        <p class="gray2 font-size3 mb-0">
                            {{ $article->updated_at->toFormattedDateString() }}
                        </p>
                    </div>
                </div>

                <div class="py-2"></div>

                {{-- Body --}}
                <article class="tinymce-editor-contents">
                    {!! $article->body !!} <br>
                </article>

                <hr>


                {{-- Published By --}}
                <div>
                    {{-- Share Buttons --}}
                    <div class="shareIcons"></div>

                    <div class="py-1"></div>

                    <p class="gray2 text-uppercase font-size3">Published By</p>

                    <div class="d-flex justify-content-start align-items-start">
                        <a href="{{ $article->user->show_url }}">
                            <img src="{{ $article->user->avatar }}" class="avatar-lg mr-1" alt="Author Avatar">
                        </a>
                        <div>
                            <h4 class="font-size5 font-weight500">
                                <a href="{{ $article->user->show_url }}" class="font-size-inherit color-inherit">
                                    {{ $article->user->name }}
                                </a>
                            </h4>
                            @if(!is_null($article->user->about))
                                <h5 class="font-size3">{{ $article->user->about }}</h5>
                            @endif
                            @if(!is_null($article->user->profile_summary))
                                <p class="font-size3 gray2">{!! nl2br($article->user->profile_summary) !!}</p>
                            @endif
                        </div>
                    </div>
                </div>

                <div class="py-1"></div>

            </div>
        </div>
    </div>

    <div class="py-4"></div>

    @if(count($article->getMoreArticlesByUsers() ?? []))
        <section class="recommended-articles mb-1">
            <h6 class="font-size5 border-bottom pb-2 mb-2"><b>More Articles by {{ $article->user->username }}</b></h6>
            <div class="row">
                @foreach($article->getMoreArticlesByUsers() as $article)
                    <div class="col-12 col-lg-4 mb-2">
                        @component('forum.users.profile.articles.common.block', ['article' => $article])
                        @endcomponent
                    </div>
                @endforeach
            </div>
        </section>
    @endif
</div>

@endsection