routes/web.php
            Route::patch('{id}/update', 'Voyager\VoyagerGuideController@update')->name('.update');
        });

        // Generate Topical Exam Builder Sheets
        Route::prefix('/exam-builder-sheets')->name('voyager.exam_builder_sheets')->group(function(){
            Route::get('topical/generate', 'Voyager\VoyagerExamBuilderSheetController@getGenerateTopicalView')->name('.topical.get_generate_view');
            Route::post('topical/generate', 'Voyager\VoyagerExamBuilderSheetController@generateTopical')->name('.topical.generate');
        });

        // Resource
        Route::get('/resources/update_all_preview_images', 'ResourceController@updateAllPreviewImages')->name('voyager.resources.update_all_preview_images');
    });
});


// Editor File Upload
Route::post('/editor/upload', function() {
    $file = request()->file('file');
    $path = $file->store('/editor', 's3');
    return response()->json(['location' => Storage::url($path)]);
});

// Blog
Route::resource('/blog', 'BlogController')->only([
    'index', 'show'
]);
// Blog categories
Route::get('/blog/categories/{blog_category}', 'BlogCategoryController@show')->name('blog_categories.show');
// Blog authors
Route::get('/blog/author/{blog_author}', 'BlogAuthorController@show')->name('blog_authors.show');
// Contact Us
Route::get('/contact-us', 'ContactUsController@createEmail')->name('contactUs.createEmail');
Route::post('/contact-us', 'ContactUsController@sendEmail')->name('contactUs.sendEmail');

// Forum routes
Route::get('forum', 'ForumController@getLandingView')->name('forum.landing');

Route::middleware(['auth', 'exam_builder'])->prefix('exam-builder')->name('exam_builder')->group(function(){
    // Index
    Route::get('/', 'ExamBuilderController@landing')->name('.landing');
    // Create
    Route::get('/create', 'ExamBuilderController@getFilterView')->name('.get_filter_view');
    Route::post('/create', 'ExamBuilderController@filter')->name('.filter');
    Route::post('/customize', 'ExamBuilderController@customize')->name('.customize');
    // Sheets
    Route::prefix('/sheets')->name('.sheets')->group(function(){
        // Store
        Route::post('/store', 'ExamBuilderSheetController@store')->name('.store');
        Route::post('/{exam_builder_sheet}/generate-ms', 'ExamBuilderSheetController@generateAndStoreMsPdf')->name('.generate_ms');
        Route::get('/{exam_builder_sheet}/qp', 'ExamBuilderSheetController@show')->name('.show');
        Route::get('/{exam_builder_sheet}/ms', 'ExamBuilderSheetController@showMs')->name('.show_ms');
        // Download
        Route::get('/download/qp/{exam_builder_sheet}', 'ExamBuilderSheetController@downloadQp')->name('.download_qp');
        Route::get('/download/ms/{exam_builder_sheet}', 'ExamBuilderSheetController@downloadMs')->name('.download_ms');
        // Delete
        Route::delete('/{exam_builder_sheet}/delete', 'ExamBuilderSheetController@delete')->name('.delete');
    });

    Route::post('/items/{exam_builder_item}/replace', 'ExamBuilderController@replaceItem')->name('.replace_item');
    Route::post('/items/{exam_builder_item}/html', 'ExamBuilderController@getBlockHtml')->name('.get_block_html');

    // AJAX routes
    Route::get('/subjects/{subject}/paper_numbers', 'ExamBuilderController@getPaperNumbersBySubject');
});

Route::post('/s/parent', 'StudentController@getParent');

// Classroom routes
Route::middleware(['classroom'])->prefix('classroom')->name('classroom')->group(function(){
    Route::get('/', 'ClassroomController@getLandingView')->name('.landing');

    Route::middleware('auth')->group(function(){
        Route::get('/markAsRead', function(){
            if( auth()->user()->teacher ) {
                auth()->user()->teacher->unreadNotifications->markAsRead();
            } elseif( auth()->user()->student ) {
                auth()->user()->student->unreadNotifications->markAsRead();
            } elseif( auth()->user()->parent ) {
                auth()->user()->parent->unreadNotifications->markAsRead();
            }
        })->name('.markAsRead');

        // Calendar
        Route::get('calendar', 'ClassroomController@calendar')->name('.calendar');

        // AJAX
        Route::post('/t/s/unreported_lessons', 'ClassroomTeacherController@getUnreportedLessons');
        Route::post('/t/s/unpaid_lessons', 'ClassroomTeacherController@getUnpaidLessons');

        // Classrooms
        Route::prefix('classrooms')->name('.classrooms')->group(function(){
            Route::get('/', 'ClassroomController@index')->name('.index');
            Route::get('/create', 'ClassroomController@create')->name('.create');
            Route::post('/store', 'ClassroomController@store')->name('.store');
            // Edit classroom
            Route::get('/{classroom}/edit', 'ClassroomController@edit')->name('.edit');
            Route::patch('/{classroom}/update', 'ClassroomController@update')->name('.update');
            // Delete classroom
            // Route::delete('/{classroom}/delete', 'ClassroomController@delete')->name('.delete');
            Route::get('/{classroom}/dashboard', 'ClassroomController@show')->name('.show');
            // Add student to classroom
            Route::get('/{classroom}/students', 'ClassroomClassroomStudentController@index')->name('.students.index');
            Route::get('/{classroom}/add', 'ClassroomClassroomStudentController@getAddView')->name('.students.get_add_view');
            Route::post('/{classroom}/add', 'ClassroomClassroomStudentController@add')->name('.students.add');
            // Kick student from classroom
            Route::post('/{classroom}/remove', 'ClassroomClassroomStudentController@remove')->name('.students.remove');
            // Join Classroom
            Route::get('/join', 'ClassroomClassroomStudentController@getJoinClassView')->name('.students.getJoinClassView');
            Route::post('/join', 'ClassroomClassroomStudentController@join')->name('.students.join');
        });

        // Classroom-specific routes
        Route::prefix('{classroom}')->group(function(){
            // Progress in Class
            Route::get('/progress', 'StudentController@show_progress_in_class')->name('.progress');

            // Lessons
            Route::prefix('/lessons')->name('.lessons')->group(function(){
                Route::get('/', 'ClassroomLessonController@index')->name('.index');
                Route::get('/create', 'ClassroomLessonController@create')->name('.create');
                Route::post('/store', 'ClassroomLessonController@store')->name('.store');
                Route::get('/{lesson}', 'ClassroomLessonController@show')->name('.show');

                Route::get('/{lesson}/edit', 'ClassroomLessonController@edit')->name('.edit');
                Route::patch('/{lesson}', 'ClassroomLessonController@update')->name('.update');
                Route::delete('/{lesson}', 'ClassroomLessonController@destroy')->name('.destroy');
            });

            Route::name('.posts')->group(function(){
                Route::get('/discussion', 'ClassroomClassroomPostController@index')->name('.index');
                Route::prefix('/posts')->group(function(){
                    Route::get('/create', 'ClassroomClassroomPostController@create')->name('.create');
                    Route::post('/store', 'ClassroomClassroomPostController@store')->name('.store');
                    // Route::get('/{post}', 'ClassroomClassroomPostController@show')->name('.show');

                    Route::get('/{post}/edit', 'ClassroomClassroomPostController@edit')->name('.edit');
                    Route::patch('/{post}', 'ClassroomClassroomPostController@update')->name('.update');
                    Route::delete('/{post}', 'ClassroomClassroomPostController@destroy')->name('.delete');
                });
            });
        });

        // Students
        Route::prefix('/students')->name('.students')->group(function(){
            Route::get('', 'ClassroomStudentController@index')->name('.index');
            Route::get('/{student}', 'ClassroomStudentController@show')->name('.show');
        });

        // Children
        Route::prefix('/children')->name('.children')->group(function(){
            Route::get('/', 'ClassroomChildrenController@index')->name('.index');
            Route::get('/{student}', 'ClassroomStudentController@show')->name('.show');
        });

        // Reports
        Route::prefix('reports')->name('.reports')->group(function(){
            Route::get('/', 'ClassroomStudentReportController@index')->name('.index');
            Route::get('/create', 'ClassroomStudentReportController@create')->name('.create');
            Route::post('/store', 'ClassroomStudentReportController@store')->name('.store');
            Route::get('/{report}/show', 'ClassroomStudentReportController@show')->name('.show');
            Route::post('/{report}/download_pdf', 'ClassroomStudentReportController@download_pdf')->name('.download_pdf');
            Route::delete('/{report}/delete', 'ClassroomStudentReportController@delete')->name('.delete');
        });

        // // Invoices
        // Route::prefix('invoices')->name('.invoices')->group(function(){
        //     Route::get('/', 'ClassroomInvoiceController@index')->name('.index');
        //     Route::get('/create', 'ClassroomInvoiceController@create')->name('.create');
        //     Route::post('/store', 'ClassroomInvoiceController@store')->name('.store');
        //     Route::get('/{teacher_invoice}/show', 'ClassroomInvoiceController@show')->name('.show');
        //     Route::post('/{teacher_invoice}/mark-as-paid', 'ClassroomInvoiceController@mark_as_paid')->name('.mark_as_paid');
        //     Route::delete('/{teacher_invoice}/delete', 'ClassroomInvoiceController@delete')->name('.delete');
        //     Route::post('/{teacher_invoice}/download_pdf', 'ClassroomInvoiceController@download_pdf')->name('.download_pdf');
        // });

app/Guide.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use Illuminate\Database\Eloquent\SoftDeletes;

class Guide extends Model
{
    use SoftDeletes;

    protected $guarded = [];

    public function exam_board()
    {
        return $this->subject->exam_board;
    }

    public function subject()
    {
        return $this->belongsTo(Subject::class, 'subject_id', 'id');
    }

    public function chapter()
    {
        return $this->belongsTo(Chapter::class);
    }

    public function topic()
    {
        return $this->belongsTo(Chapter::class);
    }

    public function resource()
    {
        return $this->morphOne('App\Resource', 'resourceable');
    }

    /**
     * Returns author of guides (fallback to user with admin resource email)
     * @return App\User
     */
    public function getAuthor()
    {
        return !is_null($this->user_id) ? User::find($this->user_id)
                                        : User::where('email', setting('admin.resource_email'))->first();
    }

    /**
     * -------------
     * Accessors
     * -------------
     */

    public function getNameAttribute()
    {
        return $this->title;
    }

    public function getImgAttribute($value)
    {
        if($value){
            if(strpos($value, 'amazonaws')){
                //Amazon link for image
                return $value;
            } else{
                //Amazon S3
                $updated_value = str_replace('\\', '/', $value);
                return Storage::cloud()->url($updated_value);
            }
        } else {
            return null;
        }
    }

    public function getPrimaryAttribute()
    {
        return $this->title;
    }

    public function getSecondaryAttribute()
    {
        return $this->description;
    }

    /**
     * Return show url
     * @return string
     */
    public function getShowUrlAttribute()
    {
        try {
            return route('guides.show', [$this->subject->exam_board->slug, $this->id]);
        } catch(\Exception $e) {
            return null;
        }
    }

    public function getUrlAttribute()
    {
        return $this->show_url;
    }

    /**
     * Get previous guide by ID
     * @return App\Guide $guide
     */
    public function prev()
    {
        // get previous user id
        $previous_id = self::where('id', '<', $this->id)->where('chapter_id', $this->chapter_id)->max('id');
        return self::find($previous_id);
    }

    /**
     * Get next guide by ID
     * @return App\Guide $guide
     */
    public function next()
    {
        $next_id = self::where('id', '>', $this->id)->where('chapter_id', $this->chapter_id)->min('id');
        return self::find($next_id);
    }

    /**
     * Get guides from same subject (max 5)
     * @param int $take Number of guides to retrieve
     * @return Collection
     */
    public function similarBySubject($take = 5)
    {
        return self::where('id', '!=', $this->id)->where('subject_id', $this->subject->id)->inRandomOrder()->take($take)->get();
    }

    /**
     * Get guides from same chapter (max 5)
     * @param int $take Number of guides to retrieve
     * @return Collection
     */
    public function similarByChapter($take = 5)
    {
        return self::where('id', '!=', $this->id)->where('chapter_id', $this->chapter->id)->inRandomOrder()->take($take)->get();
    }

    /**
     * Returns true if guide is general (non-chapter-specific)
     * @return boolean
     */
    public function isGeneral()
    {
        return is_null($this->chapter_id);
    }
}

resources/views/classroom/classrooms/common/block.blade.php
@if( isset($room) && !is_null($room) )
    <div class="panel position-relative scale-on-hover fast border-left-blue5-3px h-100">
        <a href="{{ route('classroom.classrooms.show', $room->id) }}" class="stretched-link"></a>
        <div class="mt-1">
            <h3 class="font-size5 font-weight500">{{ $room->name }}</h3>
            <div class="mb-1">
                <h4 class="gray2 font-size2 mb-1">{{ $room->subject->exam_board_and_name }}</h4>
                <h4 class="gray2 font-size2 mb-0">{{ count($room->students ?? []) }} @if(count($room->students ?? []) > 1) students @else student @endif</h4>
            </div>
        </div>
    </div>
@else
    <div class="panel position-relative scale-on-hover fast border-left-blue5-3px h-100">
        <a href="{{ $url }}" class="stretched-link"></a>

        <div class="d-flex flex-column justify-content-center align-items-center mt-1 mb-1">
            <span class="iconify blue5 mb-2" data-icon="bi:plus-circle-fill" data-inline="false" style="font-size: 48px;"></span>
            <h4 class="gray2 font-size2 mb-0">{{ $title }}</h4>
        </div>
    </div>
@endif

resources/views/classroom/classrooms/common/key_value_block.blade.php
<div class="card border-left-{{ $datum['color'] }} h-100 py-2">
    <div class="card-body">
        <div class="row no-gutters align-items-center">
            <div class="col mr-2">
                <div class="text-xs font-weight-bold text-{{ $datum['color'] }} text-uppercase mb-1">{{ $datum['key'] }}</div>
                <div class="h5 mb-0 font-weight-bold text-gray-800">{{ $datum['value'] }}</div>
            </div>
            <div class="col-auto">
                <i class="{{ $datum['icon'] }} text-gray-300"></i>
            </div>
        </div>
    </div>
</div>

resources/views/classroom/classrooms/common/list.blade.php
<div class="panel p-0 mb-3">
    <div class="panel-header m-0">
        {{ $title }}
        @if(isset($subtitle) && !is_null($subtitle))
            <span class="font-weight-normal gray2 font-size1">{{ $subtitle }}</span>
        @endif
    </div>
    <div class="panel-body p-0">
        @if( $collection->count() )
            @if( $type == 'student' )
                @foreach($collection as $item)
                    <div class="position-relative @if(!$loop->last) border-bottom @endif p-2 d-flex justify-content-between align-items-center">
                        @component('classroom.common.student_avatar', ['student' => $item, 'classroom' => $classroom])
                        @endcomponent

                        <div>
                            @can('view_student', $classroom)
                                <a href="{{ $item->url( $classroom ) }}" class="button--primary sm">View</a>
                            @endcan
                            @can('remove_student', $classroom)
                                <form class="d-inline-block" action="{{ route('classroom.classrooms.students.remove', $classroom->id) }}" method="POST">
                                    @csrf
                                    <input type="hidden" name="student_user_id" value="{{ $item->user_id }}">
                                    <button type="submit" class="button--danger sm deleteButton">Remove</button>
                                </form>
                            @endcan
                        </div>
                    </div>
                @endforeach
            @else
                @foreach($collection as $item)
                    <div class="position-relative @if(!$loop->last) border-bottom @endif p-2 white-hoverable">
                        <a href="{{ $item->url }}" class="stretched-link"></a>
                        <h4 class="font-weight500 mb-1">{{ $item->primary }}</h4>
                        <p class="font-size1 gray2 mb-0">{!! $item->secondary !!}</p>
                    </div>
                @endforeach
            @endif
        @else
            <div class="py-2">
                <p class="py-2 text-center gray2 mb-0">No {{ $type }} found</p>
            </div>
        @endif
        @if( isset($url) && !is_null($url) )
            <a class="d-block p-2 hover-on-underline border-top" href="{{ $url }}">Show more {{ $type.'s' }} ></a>
        @endif
    </div>
</div>